<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * articuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articuloRepository extends EntityRepository
{
	public function getArticulosPorTema($temaId)
    {
	$qp = $this->createQueryBuilder('a')->select('a')->where('a.tema = :tema_id')->setParameter('tema_id', $temaId);
	return $qp->getQuery()->getResult();
    }
}
