<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * articuloporautorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articuloporautorRepository extends EntityRepository
{
    public function getArticulos($id)
    {
	$qp = $this->createQueryBuilder('a')->select('a')->where('a.autor = :id')->setParameter('id', $id);
	return $qp->getQuery()->getResult();
    }

    public function getAllArticulos($id): array
    {
       $query = $this->getEntityManager()->createQuery(
       'SELECT ar
        FROM AppBundle\Entity\articuloporautor ap, AppBundle\Entity\articulo ar, AppBundle\Entity\autor au
        WHERE ar.id = ap.articulo and ap.autor = :autorId'
        )->setParameter('autorId', $id);
      return $query->execute();
    }
}
