<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentRepository extends EntityRepository
{
	public function getCommentsPorArticulo($articuloId, $approved = true)
    {
	$qp = $this->createQueryBuilder('c')->select('c')->where('c.articulo = :articulo_Id')->addOrderBy('c.created')->setParameter('articulo_Id', $articuloId);

	if (false === is_null($approved))
		$qp->andWhere('c.approved = :approved')->setParameter('approved', $approved);

	return $qp->getQuery()->getResult();
    }
}
